[package]
name = "School-mangament"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }
tokio = { version = "1.38.0", features = ["full"] }